---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: eks-demo-2
  name: deployment-eks-demo
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: app-eks-demo
  replicas: 2
  template:
    metadata:
      labels:
        app.kubernetes.io/name: app-eks-demo
    spec:
      containers:
      - image: CONTAINER_IMAGE
        imagePullPolicy: Always
        name: app-eks-demo
        ports:
        - containerPort: 80